---
output:   
  pdf_document:
    keep_tex: true
---


### Qualitative comparison of policy settings


|  Issue  |  Activist-backed FSC-US  |  Industry-backed SFI  |
|:------------------------|:--------------------------------------------|:--------------------------------------------|
|Indigenous peoples' rights | Recognize and uphold rights, customs, culture including UNDRIP. No threat to rights or resources. Free, prior, and informed consent on public and private lands. Engage indigenous peoples and consult with affected groups. Cooperate to identify and protect significant sites. Compensate for indigenous knowledge and utilize as requested. | A written policy acknowledging a commitment to recognize and respect rights. |
|Public Reporting and Consultation | Required on public and private lands. | Required on public lands. | 
|Forest conversion to non-forest | Prohibited except limited areas where clear, substantial, additional, secure, long-term conservation benefits. | No specific policy.| 
|Old growth forest | Old growth is normally mapped as conservation forest. Only restoration management on public land. Legacy trees not harvested. Maintain structure, composition, and processes. A portion of the forest is restored where old growth would naturally occur. | Support and participate in programs for old growth conservation in the region — no identification or restoration requirements.
|Protected areas | Conserve or restore a representative area of natural ecosystems. Assess and maintain environmental values and necessary conservation measures. | No specific policy.|
|Threatened and Endangered Species | Survey and report or assume the presence of vulnerable, imperiled, and critically imperiled. Maintain habitat & viable populations. | Program to protect threatened and endangered species and known sites. Protect viable occurrences of critically imperiled or imperiled species.|
|Workers' right to organize | Freedom to associate and advocate |
Develop dispute resolution. | Obey law. Train on worker rights. |
|Wages | Meets local norms | Written commitment to comply with social law prevailing wage. Train on wage rules. |
|Safety | posted safety guidelines, contracts include safety, records kept | Written commitment to comply with OSHA. Training on OSHA |







|Threatened and Endangered Species | Gap analysis, identify and establish representative sample areas, survey for listed, candidate, G1-G3, S1-S3, and N1-N3 designated species or assume presence, report findings. Permanent protection of representative sample of all habitats, conservation zones support viable populations. | Program to locate G1-G2 species through credible system, use NatureServe or equivalent. Protect or manage special sites and sites with special conservation value including vernal pools of ecological significance, and sites with species at risk. | 

|Indigenous use rights | Access and use rights documented, identified on maps | Identify and protect culturally important sites. |
|Indigenous consultation | Identify and contact American Indian groups via designated tribal representatives for legal or customary use rights, ensure no impact on rights, protocols jointly developed and signed by tribes in formal consultation, informed written consent, identify special sites and protected areas. | Confer with affected indigenous peoples on public lands.
|Indigenous knowledge | Understand and respect traditional knowledge. | Identify knowledge used, fairly compensate for use. |
